services:
  - type: web
    name: openapi-mcp
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python mcp-server/src/main.py
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      - name: FASTMCP_EXPERIMENTAL_ENABLE_NEW_OPENAPI_PARSER
        value: true
        
